name: Deploy Frontend (Dev Mode)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }} 
          username: ${{ secrets.VPS_USER }}  
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd devstore/weath-sensor/weath-client
            pkill -f "npm run dev" || echo "No dev process to kill"
            git pull origin main
            npm install
            npm run dev
            echo "Deployment complete!"
